name: Zadanie 2 Moroz
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sprawdzanie repo
        uses: actions/checkout@v2

      - name: Ustawienie QEMU
        uses: docker/setup-qemu-action@v1

      - name: Ustawienie Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push x86_64 image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/zadanie2/zadanie2:latest


      - name: Build and push arm64 image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/arm64

      - name: Testowanie CVE
        run: |
          docker pull zadanie2
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy zadanie2

      - name: Publikowanie obrazy na github
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          registry: ghcr.io
          repository: zadanie2/zadanie2
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
